---
pagetitle: Publications
---

<!-- THESE LINES OF R CODE CREATE THE LIST OF ARTICLES TO CITE -->
<!-- library("bibtex") -->
<!-- refs = read.bib(file = "refs.bib") -->
<!-- for (i in 1:length(refs)){ -->
<!--   print(refs[[i]]) -->
<!--   cat("<br><br>") -->
<!-- } -->


<br><br>
For the most up to date list of publications, check out my <a href="https://scholar.google.com/citations?user=4empyKkAAAAJ&hl=en">Google Scholar</a> page.

<b>Peer-reviewed Publications</b><br>
Rieken M, Djajadiningrat RS, Kluth LA, Favaretto RL, Xylinas E, Guimaraes GC, Soares FA,
Kent M, **Sjoberg DD**, Horenblas S and others (2014). “Predictors of cancer-specific mortality
after disease recurrence in patients with squamous cell carcinoma of the penis.” _European
urology_, *66*(5), pp. 811-814.
<br><br>Silberstein JL, Poon SA, **Sjoberg DD**, Maschino AC, Vickers AJ, Bernie A, Konety BR, Kevin
Kelly W and Eastham JA (2015). “Long-term oncological outcomes of a phase II trial of
neoadjuvant chemohormonal therapy followed by radical prostatectomy for patients with
clinically localised, high-risk prostate cancer.” _BJU international_, *116*(1), pp. 50-56.
<br><br>Bochner BH, **Sjoberg DD** and Laudone VP (2014). “A randomized trial of robot-assisted
laparoscopic radical cystectomy.” _New England Journal of Medicine_, *371*(4), pp. 389-390.
<br><br>Kim PH, Sukhu R, Cordon BH, Sfakianos JP, **Sjoberg DD**, Hakimi AA, Dalbagni G, Lin O and Herr
HW (2014). “Reflex fluorescence in situ hybridization assay for suspicious urinary cytology
in patients with bladder cancer with negative surveillance cystoscopy.” _BJU international_,
*114*(3), pp. 354-359.
<br><br>Breitbart W, Poppito S, Rosenfeld B, Vickers AJ, Li Y, Abbey J, Olden M, Pessin H,
Lichtenthal W, **Sjoberg D** and others (2012). “Pilot randomized controlled trial of individual
meaning-centered psychotherapy for patients with advanced cancer.” _Journal of Clinical
Oncology_, *30*(12), pp. 1304.
<br><br>Vickers AJ, Ulmert D, **Sjoberg DD**, Bennette CJ, Björk T, Gerdtsson A, Manjer J, Nilsson PM,
Dahlin A, Bjartell A and others (2013). “Strategy for detection of prostate cancer based on
relation between prostate specific antigen at age 40-55 and long term risk of metastasis:
case-control study.” _Bmj_, *346*, pp. f2023.
<br><br>Tarin TV, Power NE, Ehdaie B, Sfakianos JP, Silberstein JL, Savage CJ, **Sjoberg D**, Dalbagni G
and Bochner BH (2012). “Lymph node-positive bladder cancer treated with radical cystectomy
and lymphadenectomy: effect of the level of node positivity.” _European urology_, *61*(5),
pp. 1025-1030.
<br><br>Cassileth BR, Van Zee KJ, Yeung KS, Coleton MI, Cohen S, Chan YH, Vickers AJ, **Sjoberg DD** and
Hudis CA (2013). “Acupuncture in the treatment of upper-limb lymphedema.” _Cancer_,
*119*(13), pp. 2455-2461.
<br><br>Rink M, **Sjoberg D**, Comploj E, Margulis V, Xylinas E, Lee RK, Hansen J, Cha EK, Raman JD,
Remzi M and others (2012). “Risk of cancer-specific mortality following recurrence after
radical nephroureterectomy.” _Annals of surgical oncology_, *19*(13), pp. 4337-4344.
<br><br>Margulis V, Shariat SF, Rapoport Y, Rink M, **Sjoberg DD**, Tannir NM, Abel EJ, Culp SH, Tamboli
P and Wood CG (2013). “Development of accurate models for individualized prediction of
survival after cytoreductive nephrectomy for metastatic renal cell carcinoma.” _European
urology_, *63*(5), pp. 947-952.
<br><br>Vickers AJ, **Sjoberg D**, Basch E, Sculli F, Shouery M, Laudone V, Touijer K, Eastham J and
Scardino PT (2012). “How do you know if you are any good? A surgeon performance feedback
system for the outcomes of radical prostatectomy.” _European urology_, *61*(2), pp. 284-289.
<br><br>Touijer KA, Mazzola CR, **Sjoberg DD**, Scardino PT and Eastham JA (2014). “Long-term outcomes
of patients with lymph node metastasis treated with radical prostatectomy without adjuvant
androgen-deprivation therapy.” _European urology_, *65*(1), pp. 20-25.
<br><br>Rink M, Lee DJ, Kent M, Xylinas E, Fritsche H, Babjuk M, Brisuda A, Hansen J, Green DA, Aziz
A and others (2013). “Predictors of cancer-specific mortality after disease recurrence
following radical cystectomy.” _BJU international_, *111*(3b).
<br><br>Carlsson SV, Tafe LJ, Chade DC, **Sjoberg DD**, Passoni N, Shariat SF, Eastham J, Scardino PT,
Fine SW and Touijer KA (2013). “Pathological features of lymph node metastasis for
predicting biochemical recurrence after radical prostatectomy for prostate cancer.” _The
Journal of urology_, *189*(4), pp. 1314-1319.
<br><br>Deng G, Chan Y, **Sjoberg D**, Vickers A, Yeung KS, Kris M, Straus D and Cassileth B (2013).
“Acupuncture for the treatment of post-chemotherapy chronic fatigue: a randomized, blinded,
sham-controlled trial.” _Supportive Care in Cancer_, *21*(6), pp. 1735-1741.
<br><br>Bancroft EK, Page EC, Castro E, Lilja H, Vickers A, **Sjoberg D**, Assel M, Foster CS, Mitchell
G, Drew K and others (2014). “Targeted prostate cancer screening in BRCA1 and BRCA2 mutation
carriers: results from the initial screening round of the IMPACT study.” _European urology_,
*66*(3), pp. 489-499.
<br><br>Carlsson S, Assel M, **Sjoberg D**, Ulmert D, Hugosson J, Lilja H and Vickers A (2014).
“Influence of blood prostate specific antigen levels at age 60 on benefits and harms of
prostate cancer screening: population based cohort study.” _Bmj_, *348*, pp. g2296.
<br><br>Sankin A, Sfakianos JP, Schiff J, **Sjoberg D** and Coleman JA (2012). “Assessing renal function
after partial nephrectomy using renal nuclear scintigraphy and estimated glomerular
filtration rate.” _Urology_, *80*(2), pp. 343-346.
<br><br>Christensson A, Savage C, **Sjoberg DD**, Cronin AM, Frank O'Brien M, Lowrance W, Nilsson PM,
Vickers AJ, Russo P and Lilja H (2013). “Association of cancer with moderately impaired
renal function at baseline in a large, representative, population-based cohort followed for
up to 30 years.” _International journal of cancer_, *133*(6), pp. 1452-1458.
<br><br>Vickers AJ, **Sjoberg DD**, Ulmert D, Vertosick E, Roobol MJ, Thompson I, Heijnsdijk EA, De
Koning H, Atoria-Swartz C, Scardino PT and others (2014). “Empirical estimates of prostate
cancer overdiagnosis by age and prostate-specific antigen.” _BMC medicine_, *12*(1), pp. 26.
<br><br>Braun K, Ahallal Y, **Sjoberg DD**, Ghoneim T, Esteban MD, Mulhall J, Vickers A, Eastham J,
Scardino PT and Touijer KA (2014). “Effect of repeated prostate biopsies on erectile
function in men on active surveillance for prostate cancer.” _The Journal of urology_,
*191*(3), pp. 744-749.
<br><br>Deng G, Wong WD, Guillem J, Chan Y, Affuso T, Yeung KS, Coleton M, **Sjoberg D**, Vickers A and
Cassileth B (2013). “A phase II, randomized, controlled trial of acupuncture for reduction
of postcolectomy ileus.” _Annals of surgical oncology_, *20*(4), pp. 1164-1169.
<br><br>Carlsson SV, Peltola MT, **Sjoberg D**, Schröder FH, Hugosson J, Pettersson K, Scardino PT,
Vickers AJ, Lilja H and Roobol MJ (2013). “Can one blood draw replace transrectal
ultrasonography-estimated prostate volume to predict prostate cancer risk?” _BJU
international_, *112*(5), pp. 602-609.
<br><br>Vickers AJ, **Sjoberg DD**, Ankerst DP, Tangen CM, Goodman PJ and Thompson IM (2013). “The
Prostate Cancer Prevention Trial risk calculator and the relationship between
prostate-specific antigen and biopsy outcome.” _Cancer_, *119*(16), pp. 3007-3011.
<br><br>Hakimi AA, Chen L, Kim PH, **Sjoberg D**, Glickman L, Walker MR and Russo P (2013). “The impact
of metformin use on recurrence and cancer-specific survival in clinically localized
high-risk renal cell carcinoma.” _Canadian Urological Association Journal_, *7*(11-12), pp.
E687.
<br><br>Carlsson S, Berglund A, **Sjoberg D**, Khatami A, Stranne J, Bergdahl S, Lodding P, Aus G,
Vickers A and Hugosson J (2014). “Effects of surgeon variability on oncologic and functional
outcomes in a population-based setting.” _BMC urology_, *14*(1), pp. 25.
<br><br>Spaliviero M, Dalbagni G, Bochner BH, Poon BY, Huang H, Al-Ahmadie HA, Donahue TF, Taylor
JM, Meeks JJ, **Sjoberg DD** and others (2014). “Clinical outcome of patients with T1
micropapillary urothelial carcinoma of the bladder.” _The Journal of urology_, *192*(3), pp.
702-707.
<br><br>Silberstein JL, Sprenkle PC, Su D, Power NE, Tarin TV, Ezell P, **Sjoberg DD**, Feifer A,
Fleisher M, Russo P and others (2013). “Neutrophil gelatinase-associated lipocalin (NGAL)
levels in response to unilateral renal ischaemia in a novel pilot two-kidney porcine model.”
_BJU international_, *112*(4), pp. 517-525.
<br><br>Forsberg JA, **Sjoberg D**, Chen Q, Vickers A and Healey JH (2013). “Treating metastatic
disease: which survival model is best suited for the clinic?” _Clinical Orthopaedics and
Related Research®_, *471*(3), pp. 843-850.
<br><br>Musser JE, Assel M, Guglielmetti GB, Pathak P, Silberstein JL, **Sjoberg DD**, Bernstein M and
Laudone VP (2014). “Impact of routine use of surgical drains on incidence of complications
with robot-assisted radical prostatectomy.” _Journal of endourology_, *28*(11), pp.
1333-1337.
<br><br>Silberstein JL, Poon SA, **Sjoberg D**, Vickers AJ, Bernie A, Konety BR, Kelly WK and Eastham JA
(2014). “Long-term oncologic outcomes of neoadjuvant chemohormonal therapy followed by
radical prostatectomy for patients with clinically localized, high-risk prostate cancer.”
<br><br>Gondo T, Poon BY, Matsumoto K, Bernstein M, **Sjoberg DD** and Eastham JA (2015). “Clinical role
of pathological downgrading after radical prostatectomy in patients with biopsy confirmed
Gleason score 3+ 4 prostate cancer.” _BJU international_, *115*(1), pp. 81-86.
<br><br>Tarin T, Feifer A, Kimm S, Chen L, **Sjoberg D**, Coleman J and Russo P (2014). “Impact of a
common clinical pathway on length of hospital stay in patients undergoing open and minimally
invasive kidney surgery.” _The Journal of urology_, *191*(5), pp. 1225-1230.
<br><br>Tarin T, Feifer A, Kimm S, Chen L, **Sjoberg D**, Coleman J and Russo P (2014). “Impact of a
common clinical pathway on length of hospital stay in patients undergoing open and minimally
invasive kidney surgery.” _The Journal of urology_, *191*(5), pp. 1225-1230.
<br><br>Hochberg-Garrett H, Hoelscher D, Sharma S and **Sjoberg D** (2009). “The Skip to Breakfast
Project: Development, Implementation, and Evaluation of an Intervention to Increase
Healthful Breakfast Consumption among Fifth Grade Students and Their Families.” _Journal of
the American Dietetic Association_, *109*(9), pp. A81.
<br><br>**Sjoberg DD** (2015). “Toward a Smarter Prostate Cancer Screening Program.” _European urology_,
*68*(4), pp. 598-599.
<br><br>Hong SK, Poon BY, **Sjoberg DD**, Scardino PT and Eastham JA (2014). “Prostate size and adverse
pathologic features in men undergoing radical prostatectomy.” _Urology_, *84*(1), pp.
153-157.
<br><br>Touijer KA, Mazzola CR, **Sjoberg DD**, Scardino PT and Eastham JA (2014). “Reply to Michael
Froehner, Rainer Koch, and Manfred P. Wirth's Letter to the Editor re: Karim A. Touijer,
Clarisse R. Mazzola, Daniel D. Sjoberg, Peter T. Scardino, James A. Eastham. Long-term
Outcomes of Patients with Lymph Node Metastasis Treated with Radical Prostatectomy Without
Adjuvant Androgen-deprivation Therapy. Eur Urol 2014; 65: 20-5.” _European urology_,
*65*(2), pp. e25-e26.
<br><br>Sankin A, Kent M, **Sjoberg D** and Scardino PT (2014). “Does tumor grade affect the
relationship between preoperative prostate-specific antigen (PSA) and biochemical recurrence
(BCR)?”
<br><br>Ehdaie B, **Sjoberg DD**, Dalecki PH, Scardino PT, Eastham JA and Amar D (2014). “Association of
anesthesia technique for radical prostatectomy with biochemical recurrence: a retrospective
cohort study.” _Canadian Journal of Anesthesia/Journal canadien d'anesthésie_, *61*(12), pp.
1068-1074.
<br><br>Musser JE, Assel M, Mashni JW, **Sjoberg DD** and Russo P (2014). “Adult prostate sarcoma: the
Memorial Sloan Kettering experience.” _Urology_, *84*(3), pp. 624-628.
<br><br>Spaliviero M, Poon BY, Aras O, Di Paolo PL, Guglielmetti GB, Coleman CZ, Karlo CA, Bernstein
ML, **Sjoberg DD**, Russo P and others (2015). “Interobserver variability of RENAL, PADUA, and
centrality index nephrometry score systems.” _World journal of urology_, *33*(6), pp.
853-858.
<br><br>Fossati N, **Sjoberg DD**, Capitanio U, Gandaglia G, Larcher A, Nini A, Mirone V, Vickers AJ,
Montorsi F and Briganti A (2015). “Extended pelvic lymph node dissection in patients with
prostate cancer previously treated with surgery for lower urinary tract symptoms.” _BJU
international_, *116*(3), pp. 366-372.
<br><br>Mano R, Vertosick E, Sankin AI, Chevinsky MS, Larish Y, Jakubowski CD, Hötker AM, Hakimi AA,
**Sjoberg DD**, Akin O and others (2015). “Subcentimeter pulmonary nodules are not associated
with disease progression in patients with renal cell carcinoma.” _The Journal of urology_,
*193*(3), pp. 776-782.
<br><br>Hong SK, Vertosick E, **Sjoberg DD**, Scardino PT and Eastham JA (2014). “Insignificant disease
among men with intermediate-risk prostate cancer.” _World journal of urology_, *32*(6), pp.
1417-1421.
<br><br>Matignon M, Ding R, Dadhania DM, Mueller FB, Hartono C, Snopkowski C, Li C, Lee JR, Sjoberg
D, Seshan SV and others (2014). “Urinary cell mRNA profiles and differential diagnosis of
acute kidney graft dysfunction.” _Journal of the American Society of Nephrology_, pp.
ASN-2013080900.
<br><br>Parekh DJ, Punnen S, **Sjoberg DD**, Asroff SW, Bailen JL, Cochran JS, Concepcion R, David RD,
Deck KB, Dumbadze I and others (2015). “A multi-institutional prospective trial in the USA
confirms that the 4Kscore accurately identifies men with high-grade prostate cancer.”
_European urology_, *68*(3), pp. 464-470.
<br><br>Moses KA, Chen LY, **Sjoberg DD**, Bernstein M and Touijer KA (2014). “Black and White men
younger than 50 years of age demonstrate similar outcomes after radical prostatectomy.” _BMC
urology_, *14*(1), pp. 98.
<br><br>Bochner BH, Dalbagni G, **Sjoberg DD**, Silberstein J, Paz GEK, Donat SM, Coleman JA, Mathew S,
Vickers A, Schnorr GC and others (2015). “Comparing open radical cystectomy and
robot-assisted laparoscopic radical cystectomy: a randomized clinical trial.” _European
urology_, *67*(6), pp. 1042-1050.
<br><br>Vickers AJ and **Sjoberg DD** (2015). “Guidelines for reporting of statistics in European
Urology.” _European urology_, *67*(2), pp. 181-187.
<br><br>Vickers AJ and **Sjoberg DD** (2015). “Decision analysis of dutasteride use for patients with
negative prostate biopsy.” _Urology_, *85*(2), pp. 337-342.
<br><br>Bazzi WM, **Sjoberg DD**, Feuerstein MA, Maschino A, Verma S, Bernstein M, O’Brien MF, Jang T,
Lowrance W, Motzer RJ and others (2015). “Long-term survival rates after resection for
locally advanced kidney cancer: Memorial Sloan Kettering Cancer Center 1989 to 2012
experience.” _The Journal of urology_, *193*(6), pp. 1911-1917.
<br><br>Wesa KM, Segal NH, Cronin AM, **Sjoberg DD**, Jacobs GN, Coleton MI, Fleisher M, Dnistrian AM,
Saltz LB and Cassileth BR (2015). “Serum 25-hydroxy vitamin D and survival in advanced
colorectal cancer: a retrospective analysis.” _Nutrition and cancer_, *67*(3), pp. 424-430.
<br><br>Stattin P, Vickers AJ, **Sjoberg DD**, Johansson R, Granfors T, Johansson M, Pettersson K,
Scardino PT, Hallmans G and Lilja H (2015). “Improving the specificity of screening for
lethal prostate cancer using prostate-specific antigen and a panel of kallikrein markers: a
nested case-control study.” _European urology_, *68*(2), pp. 207-213.
<br><br>Selby LV, Vertosick EA, **Sjoberg DD**, Schattner MA, Janjigian YY, Brennan MF, Coit DG and
Strong VE (2015). “Morbidity after total gastrectomy: analysis of 238 patients.” _Journal of
the American College of Surgeons_, *220*(5), pp. 863-871.
<br><br>Musser JE, Assel MJ, Meeks JJ, **Sjoberg DD**, Vickers AJ, Coleman JA, Eastham JA, Parra RO,
Scardino PT, Touijer KA and others (2015). “Ambulatory Extended Recovery: Safely
Transitioning to Overnight Observation for Minimally Invasive Prostatectomy.” _Urology
Practice_, *2*(3), pp. 121-125.
<br><br>Selby LV, **Sjoberg DD**, Cassella D, Sovel M, Weiser MR, Sepkowitz K, Jones DR and Strong VE
(2015). “Comparing surgical infections in National Surgical Quality Improvement Project and
an Institutional Database.” _Journal of Surgical Research_, *196*(2), pp. 416-420.
<br><br>Fossati N, Passoni NM, Moschini M, Gandaglia G, Larcher A, Freschi M, Guazzoni G, Sjoberg
DD, Vickers AJ, Montorsi F and others (2016). “Impact of stage migration and practice
changes on high-risk prostate cancer: results from patients treated with radical
prostatectomy over the last two decades.” _BJU international_, *117*(5), pp. 740-747.
<br><br>Mano R, Kent M, Larish Y, Winer AG, Chevinsky MS, Hakimi AA, Sternberg IA, **Sjoberg DD** and
Russo P (2015). “Partial and radical nephrectomy for unilateral synchronous multifocal renal
cortical tumors.” _Urology_, *85*(6), pp. 1404-1410.
<br><br>**Sjoberg DD**, Bryant RJ, Vickers AJ, Robinson MC, Kumar R, Marsden L, Davis M, Scardino PT,
Donovan J, Neal DE and others (2015). “Predicting high-grade cancer at ten-core prostate
biopsy using four kallikrein markers measured in blood in the ProtecT study.” _JNCI: Journal
of the National Cancer Institute_, *107*(7).
<br><br>Imnadze M, **Sjoberg DD** and Vickers AJ (2016). “Adverse pathologic features at radical
prostatectomy: effect of preoperative risk on oncologic outcomes.” _European urology_,
*69*(1), pp. 143-148.
<br><br>Ehdaie B, Poon BY, **Sjoberg DD**, Recabal P, Laudone V, Touijer K, Eastham J and Scardino PT
(2016). “Variation in serum prostate-specific antigen levels in men with prostate cancer
managed with active surveillance.” _BJU international_, *118*(4), pp. 535-540.
<br><br>Anderson CB, Tin AL, **Sjoberg DD**, Mulhall JP, Sandhu J, Touijer K, Laudone VP, Eastham JA,
Scardino PT and Ehdaie B (2016). “Association between number of prostate biopsies and
patient-reported functional outcomes after radical prostatectomy: implications for active
surveillance protocols.” _BJU international_, *117*(6B).
<br><br>Sankin A, Tin AL, Mano R, Chevinsky M, Jakubowski C, Sfakianos JP, Cha EK, Yee A, Friedman
FM, **Sjoberg DD** and others (2016). “Impact of ureteroscopy before nephroureterectomy for
upper tract urothelial carcinoma on oncologic outcomes.” _Urology_, *94*, pp. 148-153.
<br><br>Cesarini M, Collins G, Ronnblom A, Santos A, **Sjoberg D**, Parkes M, Keshav S and Travis S
(2015). “Predicting the risk of acute severe colitis (ASC) at diagnosis of Ulcerative
Colitis (UC): external validation.” _Journal of Crohn's and Colitis_, *9*(suppl 1), pp.
S195-S195.
<br><br>Ghoneim TP, **Sjoberg DD**, Lowrance W, Shariat SF, Savage C, Bernstein M and Russo P (2015).
“Partial nephrectomy for renal tumors in solitary kidneys: postoperative renal function
dynamics.” _World journal of urology_, *33*(12), pp. 2023-2029.
<br><br>Braun K, **Sjoberg DD**, Vickers AJ, Lilja H and Bjartell AS (2016). “A four-kallikrein panel
predicts high-grade cancer on biopsy: independent validation in a community cohort.”
_European urology_, *69*(3), pp. 505-511.
<br><br>Fossati N, Larcher A, Gadda GM, **Sjoberg DD**, Mistretta FA, Dell’Oglio P, Lista G, Carenzi C,
Lughezzani G, Lazzeri M and others (2015). “Minimally invasive partial nephrectomy versus
laparoscopic cryoablation for patients newly diagnosed with a single small renal mass.”
_European urology focus_, *1*(1), pp. 66-72.
<br><br>Chevinsky M, Imnadze M, Sankin A, Winer A, Mano R, Jakubowski C, Mashni J, **Sjoberg DD**, Chen
Y, Tickoo SK and others (2015). “Pathological stage T3a significantly increases disease
recurrence across all tumor sizes in renal cell carcinoma.” _The Journal of urology_,
*194*(2), pp. 310-315.
<br><br>Anderson CB, Sternberg IA, Karen-Paz G, Kim PH, **Sjoberg D**, Vargas HA, Touijer K, Eastham JA
and Ehdaie B (2015). “Age is associated with upgrading at confirmatory biopsy among men with
prostate cancer treated with active surveillance.” _The Journal of urology_, *194*(6), pp.
1607-1611.
<br><br>Bazzi WM, **Sjoberg DD**, Grasso AA, Bernstein M, Parra R and Coleman JA (2015). “Predicting
length of stay after robotic partial nephrectomy.” _International urology and nephrology_,
*47*(8), pp. 1321-1325.
<br><br>Epstein JI, Zelefsky MJ, **Sjoberg DD**, Nelson JB, Egevad L, Magi-Galluzzi C, Vickers AJ,
Parwani AV, Reuter VE, Fine SW and others (2016). “A contemporary prostate cancer grading
system: a validated alternative to the Gleason score.” _European urology_, *69*(3), pp.
428-435.
<br><br>Nguyen DP, Vilaseca A, Vertosick EA, Corradi RB, Touijer KA, Benfante NE, **Sjoberg DD** and
Russo P (2016). “Histologic subtype impacts cancer-specific survival in patients with
sarcomatoid-variant renal cell carcinoma treated surgically.” _World journal of urology_,
*34*(4), pp. 539-544.
<br><br>Bazzi WM, Chen LY, Cordon BH, Mashni J, **Sjoberg DD**, Bernstein M and Russo P (2015).
“Non-neoplastic parenchymal changes in kidney cancer and post-partial nephrectomy recovery
of renal function.” _International urology and nephrology_, *47*(9), pp. 1499-1502.
<br><br>Lee JK, Assel M, Thong AE, **Sjoberg DD**, Mulhall JP, Sandhu J, Vickers AJ and Ehdaie B (2015).
“Unexpected long-term improvements in urinary and erectile function in a large cohort of men
with self-reported outcomes following radical prostatectomy.” _European urology_, *68*(5),
pp. 899-905.
<br><br>Spaliviero M, Poon BY, Karlo CA, Guglielmetti GB, Di Paolo PL, Corradi RB, Martin-Malburet
AG, Campos-Juanatey F, Escudero-Fontano E, **Sjoberg DD** and others (2016). “An arterial based
complexity (ABC) scoring system to assess the morbidity profile of partial nephrectomy.”
_European urology_, *69*(1), pp. 72-79.
<br><br>Bondarik A and Sjöberg D (2015). “Implementation of UC-EBG structure for 60 GHz gridded
parasitic patch stacked microstrip antenna.” In _Antennas and Propagation (EuCAP), 2015 9th
European Conference on_, pp. 1-5. IEEE.
<br><br>Feuerstein MA, Musser JE, Kent M, Chevinsky M, Cha EK, Kimm S, Hilton WM, **Sjoberg DD**,
Donahue TF, Vargas HA and others (2016). “Low yield of surveillance imaging after surgery
for T1 kidney cancer.” _World journal of urology_, *34*(7), pp. 949-953.
<br><br>Liu NW, Wren JD, Vertosick E, Lee JK, Power NE, Benfante NE, Kimm SY, Bains MS, **Sjoberg DD**,
Russo P and others (2016). “The prognostic impact of a positive vascular margin on pT3 clear
cell renal cell carcinoma.” _The Journal of urology_, *195*(2), pp. 264-269.
<br><br>Selby LV, Sovel M, **Sjoberg DD**, McSweeney M, Douglas D, Jones DR, Scardino PT, Soff GA,
Fabbri N, Sepkowitz K and others (2016). “Preoperative chemoprophylaxis is safe in major
oncology operations and effective at preventing venous thromboembolism.” _Journal of the
American College of Surgeons_, *222*(2), pp. 129-137.
<br><br>Punnen S, Nahar B, Prakash NS, **Sjoberg DD**, Zappala SM and Parekh DJ (2017). “The 4Kscore
predicts the grade and stage of prostate cancer in the radical prostatectomy specimen:
results from a multi-institutional prospective trial.” _European urology focus_, *3*(1), pp.
94-99.
<br><br>Mano R, Vertosick EA, Hakimi AA, Sternberg IA, **Sjoberg DD**, Bernstein M, Dalbagni G, Coleman
JA and Russo P (2016). “The effect of delaying nephrectomy on oncologic outcomes in patients
with renal tumors greater than 4 cm.” In _Urologic Oncology: Seminars and Original
Investigations_, volume 34 number 5, pp. 239-e1. Elsevier.
<br><br>Lilja H, Vickers AJ, **Sjoberg D**, Johansson R, Granfors T, Johansson M, Pettersson K, Scardino
PT, Hallmans G and Stattin P (2014). “Improving the specificity of prostate cancer screening
for early detection of lethal disease.”
<br><br>Recabal P, Assel M, **Sjoberg DD**, Lee D, Laudone VP, Touijer K, Eastham JA, Vargas HA, Coleman
J and Ehdaie B (2016). “The efficacy of multiparametric magnetic resonance imaging and
magnetic resonance imaging targeted biopsy in risk classification for patients with prostate
cancer on active surveillance.” _The Journal of urology_, *196*(2), pp. 374-381.
<br><br>Recabal P, Assel M, Musser JE, Caras RJ, **Sjoberg DD**, Coleman JA, Mulhall JP, Parra RO,
Scardino PT, Touijer K and others (2016). “Erectile function recovery after radical
prostatectomy in men with high risk features.” _The Journal of urology_, *196*(2), pp.
507-513.
<br><br>Nguyen DP, Vertosick EA, Corradi RB, Vilaseca A, Benfante NE, Touijer KA, **Sjoberg DD** and
Russo P (2016). “Histological subtype of renal cell carcinoma significantly affects survival
in the era of partial nephrectomy.” In _Urologic Oncology: Seminars and Original
Investigations_, volume 34 number 6, pp. 259-e1. Elsevier.
<br><br>Bazzi WM, Tin AL, **Sjoberg DD**, Bernstein M and Russo P (2016). “The prognostic utility of
preoperative neutrophil-to-lymphocyte ratio in localized clear cell renal cell carcinoma.”
_The Canadian journal of urology_, *23*(1), pp. 8151.
<br><br>Nahar B, Punnen S, **Sjoberg D**, Zappala SM and Parekh D (2016). “The 4Kscore to predict the
grade and stage of prostate cancer in the radical prostatectomy specimen: Results from a
multi-institutional prospective trial.”
<br><br>Nahar B, Punnen S, Zappala SM, **Sjoberg D** and Parekh D (2016). “Among men with low-grade
prostate cancer on prostate biopsy, the 4Kscore to predict prostate cancer aggressiveness at
prostatectomy.”
<br><br>Anderson C, Weber R, Patel D, Lowrance W, Mellis A, Cookson M, Lang M, Barocas D, Chang S,
Newberger E and others (2016). “A 10-item checklist improves reporting of critical
procedural elements during transurethral resection of bladder tumor.” _The Journal of
urology_, *196*(4), pp. 1014-1020.
<br><br>Vilaseca A, Nguyen DP, Vertosick EA, Corradi RB, Musquera M, Pérez M, Fossati N, **Sjoberg DD**,
Farré R, Almendros I and others (2017). “Obstructive sleep apnea and Fuhrman grade in
patients with clear cell renal cell carcinoma treated surgically.” _World journal of
urology_, *35*(1), pp. 51-56.
<br><br>Gugliemetti G, Sukhu R, Baenas MC, Meeks J, **Sjoberg D**, Eastham J, Scardino P and Touijer K
(2016). “Number of metastatic lymph nodes as determinant of outcome after salvage radical
prostatectomy for radiation-recurrent prostate cancer.” _Actas Urológicas Españolas (English
Edition)_, *40*(7), pp. 434-439.
<br><br>Preston MA, Batista JL, Wilson KM, Carlsson SV, Gerke T, **Sjoberg DD**, Dahl DM, Sesso HD,
Feldman AS, Gann PH and others (2016). “Baseline Prostate-Specific Antigen Levels in Midlife
Predict Lethal Prostate Cancer.” _Journal of clinical oncology: official journal of the
American Society of Clinical Oncology_, *34*(23), pp. 2705-2711.
<br><br>Jakubowski CD, Vertosick EA, Untch BR, **Sjoberg D**, Wei E, Palmer FL, Patel SG, Downey RJ,
Strong VE and Russo P (2016). “Complete metastasectomy for renal cell carcinoma: comparison
of five solid organ sites.” _Journal of surgical oncology_, *114*(3), pp. 375-379.
<br><br>Manley BJ, Tennenbaum DM, Vertosick EA, Hsieh JJ, **Sjoberg DD**, Assel M, Benfante NE, Strope
SA, Kim E, Casuscelli J and others (2017). “The difficulty in selecting patients for
cytoreductive nephrectomy: an evaluation of previously described predictive models.” In
_Urologic Oncology: Seminars and Original Investigations_, volume 35 number 1, pp. 35-e1.
Elsevier.
<br><br>Chen R, **Sjoberg DD**, Huang Y, Xie L, Zhou L, He D, Vickers AJ, Sun Y, Ding Q, Wei Q and
others (2017). “Prostate Specific Antigen and Prostate Cancer in Chinese Men Undergoing
Initial Prostate Biopsies Compared with Western Cohorts.” _The Journal of urology_,
*197*(1), pp. 90-96.
<br><br>Vickers A, Vertosick EA, **Sjoberg DD**, Roobol MJ, Hamdy F, Neal D, Bjartell A, Hugosson J,
Donovan JL, Villers A and others (2017). “Properties of the 4-kallikrein panel outside the
diagnostic gray zone: meta-analysis of patients with positive digital rectal examination or
prostate specific antigen 10 ng/ml and above.” _The Journal of urology_, *197*(3), pp.
607-613.
<br><br>Kim EH, Andriole GL, Crawford ED, **Sjoberg DD**, Assel M, Vickers AJ and Lilja H (2017).
“Detection of high grade prostate cancer among PLCO participants using a prespecified
4-kallikrein marker panel.” _The Journal of urology_, *197*(4), pp. 1041-1047.
<br><br>Liu N, Wren J, Vertosick E, Lee J, Power N, Benfante N, Kimm S, Bains M, **Sjoberg D**, Russo P
and others (2016). “Re: The Prognostic Impact of a Positive Vascular Margin on pT3 Clear
Cell Renal Cell Carcinoma.” _J Urol_, *195*, pp. 568e573.
<br><br>Dong Y, Vickers AJ, **Sjoberg D**, Scardino PT and Lilja H (2016). “Compositions and methods for
active surveillance of prostate cancer.” US Patent App. 15/143,329.
<br><br>O'Shaughnessy MJ, McBride SM, Vargas HA, Touijer KA, Morris MJ, Danila DC, Laudone VP,
Bochner BH, Sheinfeld J, Dayan ES and others (2017). “A pilot study of a multimodal
treatment paradigm to accelerate drug evaluations in early-stage metastatic prostate
cancer.” _Urology_, *102*, pp. 164-172.
<br><br>Nguyen D, Kent M, Vilaseca A, Corradi R, Fossati N, **Sjoberg D**, Benfante N, Eastham J,
Scardino P and Touijer K (2017). “Updated postoperative nomogram incorporating the number of
positive lymph nodes to predict disease recurrence following radical prostatectomy.”
_Prostate cancer and prostatic diseases_, *20*(1), pp. 105.
<br><br>Lee DJ, Recabal P, **Sjoberg DD**, Thong A, Lee JK, Eastham JA, Scardino PT, Vargas HA, Coleman
J and Ehdaie B (2016). “Comparative effectiveness of targeted prostate biopsy using magnetic
resonance imaging ultrasound fusion software and visual targeting: a prospective study.”
_The Journal of urology_, *196*(3), pp. 697-702.
<br><br>Winer AG, Vertosick EA, Ghanaat M, Corradi RB, Carlsson S, **Sjoberg DD**, Sankin AI, Sfakianos
JP, Cha EK, Dalbagni G and others (2017). “Prognostic value of lymph node yield during
nephroureterectomy for upper tract urothelial carcinoma.” In _Urologic Oncology: Seminars
and Original Investigations_, volume 35 number 4, pp. 151-e9. Elsevier.
<br><br>Melchart D and Dörfler W (2013). “Acupuncture for postoperative gastrointestinal
dysfunction: to treat or not to treat-is it a matter of covered eyes?” _Focus on Alternative
and Complementary Therapies_, *18*(4), pp. 201-202.
<br><br>Rosenberger LH, Weber R, **Sjoberg D**, Vickers AJ, Mangino DA, Morrow M and Pilewskie ML
(2017). “Impact of self-reported data on the acquisition of multi-generational family
history and lifestyle factors among women seen in a high-risk breast screening program: a
focus on modifiable risk factors and genetic referral.” _Breast cancer research and
treatment_, *162*(2), pp. 275-282.
<br><br>Rink M, **Sjoberg D**, Comploj E, Margulis V, Xylinas E, Lee R, Hansen J, Cha E, Raman J, Remzi
M and others (2012). “Time to Disease Recurrence is a Predictor of Cancer-Specific Mortality
After Radical Nephroureterectomy.” In _UROLOGY_, volume 80 number 3, pp. S332-S332. ELSEVIER
SCIENCE INC 360 PARK AVE SOUTH, NEW YORK, NY 10010-1710 USA.
<br><br>Gustafsson M, Vakili I, Bayer SE, **Sjoberg D** and Larsson C (2011). “Optical theorem and
forward scattering sum rule for periodic structures.” _identity_, *12*, pp. 14.
<br><br>Spaliviero M, Power N, Murray K, **Sjoberg D**, Benfante N, Bernstein M, Wren J, Russo P and
Coleman J (2017). “Phase 3 randomized trial of intravenous mannitol versus placebo prior to
renal ischemia during partial nephrectomy: Impact on renal functional outcomes.” _European
Urology Supplements_, *16*(3), pp. e369-e370.
<br><br>**Sjoberg D**, Vickers A, Assel M, Dahlin A, Carlsson S, Poon B, Ulmert D and Lilja H (2017).
“Risk of prostate-cancer death at 20 years stratified by midlife PSA and a panel of four
kallikrein markers from a representative cohort of 11,506 healthy unscreened men aged
45-74.” _European Urology Supplements_, *16*(3), pp. e418-e419.
<br><br>Dalbagni G, Benfante N, **Sjoberg DD**, Bochner BH, Machele Donat S, Herr HW, Mc Coy AS, Fahrner
AJ, Retinger C, Rosenberg JE and others (2017). “Single Arm Phase I/II Study of Everolimus
and Intravesical Gemcitabine in Patients with Primary or Secondary Carcinoma In Situ of the
Bladder who failed Bacillus Calmette Guerin (NCT01259063).” _Bladder Cancer_, *3*(2), pp.
113-119.
<br><br>Dong Y, Vickers AJ, **Sjoberg D**, Scardino PT and Lilja H (2017). “Compositions and methods for
active surveillance of prostate cancer.” US Patent App. 15/143,345.
<br><br>Zappala SM, Dong Y, Linder V, Reeve M, **Sjoberg DD**, Mathur V, Roberts R, Okrongly D, Newmark
J, Sant G and others (2017). “The 4Kscore blood test accurately identifies men with
aggressive prostate cancer prior to prostate biopsy with or without DRE information.”
_International journal of clinical practice_, *71*(6).
<br><br>Pietzak EJ, Assel M, Tennenbaum DM, Becerra M, Feldman DR, Bajorin DF, Motzer RJ, Bosl GJ,
Carver BS, **Sjoberg D** and others (2016). “The role for resection of post-chemotherapy
residual liver masses in the management of non-seminomatous germ cell tumor.”
<br><br>O'Shaughnessy M, Eastham JA, Bochner BH, Laudone VP, Carver BS, **Sjoberg D**, Scardino PT,
Scher HI and Touijer KA (2015). “Radical prostatectomy as a component of multimodal therapy
for highly selected M1 prostate cancer patients.”
<br><br>Mooney K, Berry DL, Whisenant M and **Sjoberg D** (2017). “Improving Cancer Care Through the
Patient Experience: How to Use Patient-Reported Outcomes in Clinical Practice.” In _American
Society of Clinical Oncology educational book. American Society of Clinical Oncology.
Meeting_, volume 37, pp. 695-704.
<br><br>Corradi RB, Vertosick EA, Nguyen DP, Vilaseca A, **Sjoberg DD**, Benfante N, Nogueira LN,
Spaliviero M, Touijer KA, Russo P and others (2017). “Nephrometry scores and perioperative
outcomes following robotic partial nephrectomy.” _International braz j urol_, *43*(6), pp.
1075-1083.
<br><br>Mally AD, Tin AL, Lee JK, Satasivam P, Cha EK, Donat SM, Herr HW, Bochner BH, **Sjoberg DD** and
Dalbagni G (2018). “Clinical Outcomes of Patients With T1 Nested Variant of Urothelial
Carcinoma Compared to Pure Urothelial Carcinoma of the Bladder.” _Clinical genitourinary
cancer_, *16*(1), pp. e23-e27.
<br><br>Bagrodia A, Sukhu R, Winer AG, Levy E, Vacchio M, Lee B, Pietzak EJ, Donahue TF, Cha E, Iyer
G and others (2018). “Incidence and effect of thromboembolic events in radical cystectomy
patients undergoing preoperative chemotherapy for muscle-invasive bladder cancer.” _Clinical
genitourinary cancer_, *16*(1), pp. e113-e120.
<br><br>Spaliviero M, Power NE, Murray KS, **Sjoberg DD**, Benfante NE, Bernstein ML, Wren J, Russo P
and Coleman JA (2018). “Intravenous mannitol versus placebo during partial nephrectomy in
patients with normal kidney function: a double-blind, clinically-integrated, randomized
trial.” _European urology_, *73*(1), pp. 53-59.
<br><br>Polland A, Vertosick EA, **Sjoberg DD**, Stearns GL, Leddy LS, Kollmeier MA and Sandhu JS
(2017). “Preoperative symptoms predict continence after post-radiation transurethral
resection of prostate.” _The Canadian journal of urology_, *24*(4), pp. 8903-8909.
<br><br>Takeda T, Tin AL, Corradi RB, Mamoor M, Benfante NE, **Sjoberg DD**, Scardino PT, Eastham JA,
Fine SW and Touijer KA (2018). “Topography of Prostate Cancer Recurrence After Radiation
Therapy: A Detailed Mapping Study of Salvage Radical Prostatectomy Specimens.” _European
urology_, *73*(4), pp. 488-490.
<br><br>Lee JK, **Sjoberg DD**, Miller MI, Vickers AJ, Mulhall JP and Ehdaie B (2018). “Improved
recovery of erectile function in younger men after radical prostatectomy: does it justify
immediate surgery in low-risk patients?” _European urology_, *73*(1), pp. 33-37.
<br><br>Audenet F, Vertosick EA, Fine SW, **Sjoberg DD**, Vickers AJ, Reuter VE, Eastham JA, Scardino PT
and Touijer KA (2017). “Biopsy Core Features are Poor Predictors of Adverse Pathology in Men
with Grade Group 1 Prostate Cancer.” _The Journal of urology_.
<br><br>Thong AE, Poon BY, Lee JK, Vertosick E, **Sjoberg DD**, Vickers AJ and Ehdaie B (2018).
“Concordance between patient-reported and physician-reported sexual function after radical
prostatectomy.” In _Urologic Oncology: Seminars and Original Investigations_, volume 36
number 2, pp. 80-e1. Elsevier.
<br><br>Touijer KA, Karnes RJ, Passoni N, **Sjoberg DD**, Assel M, Fossati N, Gandaglia G, Eastham JA,
Scardino PT, Vickers A and others (2017). “Survival outcomes of men with lymph node-positive
prostate cancer after radical prostatectomy: a comparative analysis of different
postoperative management strategies.” _European urology_.
<br><br>Assel M, **Sjoberg DD** and Vickers AJ (2017). “The Brier score does not evaluate the clinical
utility of diagnostic tests or prediction models.” _Diagnostic and Prognostic Research_,
*1*(1), pp. 19.
<br><br>Nguyen DP, Vertosick EA, Sharma V, Corradi RB, Vilaseca A, Takeda T, **Sjoberg DD**, Benfante N,
Fine SW, Reuter VE and others (2018). “Does subclassification of pathologically
organ-confined (pT2) prostate cancer provide prognostic discrimination of outcomes after
radical prostatectomy?” _The Journal of urology_.
<br><br>Capogrosso P, Larcher A, **Sjoberg DD**, Vertosick EA, Cianflone F, Dell’Oglio P, Carenzi C,
Salonia A, Vickers AJ, Montorsi F and others (2018). “Risk-based surveillance after surgical
treatment of renal cell carcinoma.” _The Journal of urology_.
<br><br>**Sjoberg DD**, Vickers AJ, Assel M, Dahlin A, Poon BY, Ulmert D and Lilja H (2018).
“Twenty-year Risk of Prostate Cancer Death by Midlife Prostate-specific Antigen and a Panel
of Four Kallikrein Markers in a Large Population-based Cohort of Healthy Men.” _European
urology_.
<br><br>Dowling CM, Assel M, Musser JE, Meeks JJ, **Sjoberg DD**, Bosl G, Motzer R, Bajorin D, Feldman
D, Carver BS and others (2018). “Clinical Outcome of Retroperitoneal Lymph Node Dissection
after Chemotherapy in Patients with Pure Embryonal Carcinoma in the Orchiectomy Specimen.”
_Urology_.
<br><br>